<?php

return [
    // Explicit organizational aliases; source wording is retained on each record.
    'team_aliases' => [
        'TIM KERJA PENDAPATAN, AKUNTANSI DAN ASET' => ['TIM KERJA PERBENDAHARAAN, PENDAPATAN, AKUNTANSI DAN ASET'],
        'TIM KERJA PERBENDAHARAAN' => ['TIM KERJA PERBENDAHARAAN, PENDAPATAN, AKUNTANSI DAN ASET'],
        'TIM KERJA HUKUM, HUMAS DAN SISTEM INFORMASI MANAJEMEN RUMAH SAKIT (SIMRS)' => ['TIM KERJA HUKUM, HUMAS DAN SIMRS'],
        'TIM KERJA FARMASI DAN REKAM MEDIS' => ['TIM KERJA PENINGKATAN KUALITAS LAYANAN FARMASI DAN REKAM MEDIS'],
        'TIM KERJA RADIOLOGI DAN LABORATORIUM' => ['TIM KERJA PENINGKATAN KUALITAS LAYANAN LABORATORIUM DAN RADIOLOGI'],
        'TIM KERJA PENINGKATAN KUALITAS PENUNJANG NON MEDIK' => ['TIM KERJA PENINGKATAN KUALITAS LAYANAN PENUNJANG NON MEDIK'],
        // The source combines two separate teams. Do not infer access before confirmation.
        'TIM KERJA PENDIDIKAN,PELATIHAN, PENELITIAN DAN KEPEGAWIAN' => [],
    ],
];
