import React, { useEffect, useRef, useState } from 'react';
import { Head, router, useForm } from '@inertiajs/react';
import { ArrowDownTrayIcon, ArrowPathIcon, CalendarDaysIcon, ChevronLeftIcon, ChevronRightIcon, FolderOpenIcon, LockClosedIcon, MagnifyingGlassIcon, PencilSquareIcon, PlusIcon, Squares2X2Icon, XMarkIcon } from '@heroicons/react/24/outline';
import App from '@/Layouts/App';
import CascadingChart from './CascadingChart';

const input = 'w-full min-w-0 rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800 shadow-sm transition focus:border-sky-500 focus:outline-none focus:ring-2 focus:ring-sky-500/20 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-500 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100 dark:disabled:bg-slate-800 dark:disabled:text-slate-400';
const action = 'inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50';
const button = `${action} bg-sky-600 text-white shadow-sm hover:bg-sky-700`;
const secondary = `${action} border border-slate-200 bg-white text-slate-600 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300 dark:hover:bg-slate-800`;
const panel = 'rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900';
const muted = 'text-sm leading-relaxed text-slate-500 dark:text-slate-400';
const levels = { 1: 'Sasaran (fitur 1)', 2: 'Program (fitur 2)', 3: 'Kegiatan (fitur 3)', 4: 'Indikator (fitur 4)' };
const parents = { 2: ['indikator_fitur1_id', '1'], 3: ['indikator_fitur2_id', '2'], 4: ['indikator_fitur3_id', '3'] };
const levelOrder = ['1', '2', '3', '4'];
const statusLabels = { draft: 'Draft', aktif: 'Aktif', ditutup: 'Ditutup' };
const Field = ({ label, children }) => <label className="block min-w-0 space-y-2 text-sm font-medium text-slate-700 dark:text-slate-300"><span>{label}</span>{children}</label>;
const Errors = ({ errors }) => Object.keys(errors).length > 0 && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-900/20 dark:text-red-300">{Object.values(errors).map((v, i) => <p key={i}>{v}</p>)}</div>;
const Status = ({ status }) => <span className={`inline-flex items-center gap-1.5 whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-semibold ${status === 'aktif' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300' : status === 'draft' ? 'bg-amber-50 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300'}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{statusLabels[status] || 'Tidak aktif'}</span>;

export default function Index({ periods, period, nodes, locations, exports, cascadingTree = [], cascadingIssues = [] }) {
    const [level, setLevel] = useState('1');
    const [search, setSearch] = useState('');
    const [editing, setEditing] = useState(false);
    const [tab, setTab] = useState('bagan');
    const [page, setPage] = useState(1);
    const [showCreate, setShowCreate] = useState(!period);
    const editor = useRef(null);
    const create = useForm({ tahun: (periods[0]?.tahun || new Date().getFullYear()) + 1, source_period_id: period?.id || '' });
    const metadata = useForm({ nama_organisasi: period?.nama_organisasi || '', tujuan: period?.tujuan || '', status: period?.status || 'draft' });
    const node = useForm({});
    const mapping = useForm({ source_indicator_id: '', target_period_id: period?.id || '', target_indicator_id: '' });
    useEffect(() => {
        metadata.setData({ nama_organisasi: period?.nama_organisasi || '', tujuan: period?.tujuan || '', status: period?.status || 'draft' });
        mapping.setData({ source_indicator_id: '', target_period_id: period?.id || '', target_indicator_id: '' });
        create.setData('source_period_id', period?.id || '');
        setEditing(false);
        setPage(1);
    }, [period?.id, period?.status]);
    useEffect(() => { setPage(1); }, [level, search]);
    useEffect(() => { if (editing) editor.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }, [editing, node.data.id]);
    const begin = (item = {}) => {
        node.clearErrors();
        node.setData({ id: item.id || '', name: item.name || '', tujuan: item.tujuan || '', jabatan: item.jabatan || '', kode_cascading: item.kode_cascading || '', sort_order: item.sort_order || 0, is_active: item.is_active === undefined ? true : !!item.is_active,
            ...(parents[level] ? { [parents[level][0]]: item[parents[level][0]] || '' } : {}),
            location_id: level === '4' ? (Array.isArray(item.location_id) ? item.location_id : [].concat(JSON.parse(item.location_id || '[]'))) : item.location_id || '' });
        setEditing(true);
    };
    const options = (items) => <><option value="">Pilih</option>{(items || []).map(x => <option key={x.id} value={x.id}>#{x.id} {x.name}</option>)}</>;
    const canEdit = period?.status === 'draft';
    const rows = (nodes[level] || []).filter(x => `${x.name} ${x.jabatan || ''} ${x.display_code || x.kode_cascading || ''} ${x.id}`.toLowerCase().includes(search.toLowerCase()));
    const pageCount = Math.max(1, Math.ceil(rows.length / 15));
    const currentPage = Math.min(page, pageCount);
    const visibleRows = rows.slice((currentPage - 1) * 15, currentPage * 15);
    const indicatorCount = levelOrder.reduce((sum, key) => sum + (nodes[key]?.length || 0), 0);
    return <div className="min-w-0 space-y-6 text-slate-800 dark:text-slate-100">
        <Head title="Indikator Tahunan dan Cascading" />
        <header className="flex flex-col justify-between gap-5 xl:flex-row xl:items-center">
            <div className="min-w-0 space-y-2"><p className="text-xs font-semibold uppercase tracking-widest text-sky-600 dark:text-sky-400">Master data / Kinerja</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Indikator Tahunan & Cascading</h1><p className={muted}>Kelola sasaran dan indikator setiap tahun, lalu susun dokumen Cascading.</p></div>
            <div className="flex shrink-0 flex-wrap gap-2"><button type="button" className={secondary} aria-expanded={showCreate} aria-controls="create-period" onClick={() => setShowCreate(!showCreate)}><PlusIcon className="h-4 w-4" />Buat tahun baru</button>{period && <a className={button} href={route('kinerja.export', period.id)}><ArrowDownTrayIcon className="h-4 w-4" />Ekspor Cascading</a>}</div>
        </header>
        {showCreate && <section id="create-period" className={`${panel} border-sky-200 p-5 dark:border-sky-900 sm:p-6`}>
            <div className="mb-5 flex items-start justify-between gap-3"><div><h2 className="font-semibold">Siapkan periode tahun baru</h2><p className={`mt-1 ${muted}`}>Salin struktur tahun sebelumnya atau mulai kosong. Periode baru disimpan sebagai draft.</p></div><button type="button" className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 focus-visible:ring-2 focus-visible:ring-sky-500 dark:hover:bg-slate-800" aria-label="Tutup formulir tahun baru" onClick={() => setShowCreate(false)}><XMarkIcon className="h-5 w-5" /></button></div>
            <form className="space-y-4" onSubmit={e => { e.preventDefault(); create.post(route('kinerja.store'), { onSuccess: () => setShowCreate(false) }); }}>
                <div className="grid items-end gap-4 sm:grid-cols-2 xl:grid-cols-3"><Field label="Tahun baru"><input className={input} type="number" min="2000" max="2100" value={create.data.tahun} onChange={e => create.setData('tahun', e.target.value)} required /></Field><Field label="Salin hierarki dari"><select className={input} value={create.data.source_period_id} onChange={e => create.setData('source_period_id', e.target.value)}><option value="">Mulai kosong</option>{periods.map(p => <option key={p.id} value={p.id}>{p.tahun} — {statusLabels[p.status]}</option>)}</select></Field><button className={`${button} justify-self-start`} disabled={create.processing}><PlusIcon className="h-4 w-4" />{create.processing ? 'Membuat draft…' : 'Buat draft'}</button></div><Errors errors={create.errors} />
            </form>
        </section>}
        <section className={`${panel} overflow-hidden`}>
            <div className="flex flex-col gap-5 p-5 sm:p-6 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 items-center gap-4"><div className="hidden rounded-2xl bg-sky-50 p-3 text-sky-600 dark:bg-sky-900/30 dark:text-sky-400 sm:block"><CalendarDaysIcon className="h-7 w-7" /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-bold">{period ? `Periode ${period.tahun}` : 'Pilih periode kinerja'}</h2>{period && <Status status={period.status} />}</div><p className={`mt-1 break-words ${muted}`}>{period?.nama_organisasi || 'Sasaran dan indikator dikelompokkan berdasarkan tahun.'}</p></div></div><div className="w-full shrink-0 lg:w-52"><Field label="Tahun data"><select className={input} value={period?.tahun || ''} onChange={e => router.get(route('kinerja.index'), { tahun: e.target.value })}><option value="" disabled>Pilih tahun</option>{periods.map(p => <option key={p.id} value={p.tahun}>{p.tahun} — {statusLabels[p.status]}</option>)}</select></Field></div></div>
            {period && <div className="grid grid-cols-3 divide-x divide-slate-200 border-t border-slate-200 bg-slate-50/60 dark:divide-slate-800 dark:border-slate-800 dark:bg-slate-800/30">{[{ label: 'Sasaran (fitur 1)', count: nodes['1']?.length || 0 }, { label: 'Total data hierarki', count: indicatorCount }, { label: 'Arsip tersedia', count: exports.length }].map(({ label, count }) => <div key={label} className="p-3 sm:px-6 sm:py-4"><p className="text-xl font-bold tabular-nums">{count.toLocaleString('id-ID')}</p><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{label}</p></div>)}</div>}
        </section>
        {period?.rekonstruksi && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-relaxed text-amber-900 dark:border-amber-900/60 dark:bg-amber-900/20 dark:text-amber-200"><p className="font-semibold">Data historis perlu verifikasi</p>{period.rekonstruksi && <p className="mt-1">Periode ini direkonstruksi dari master sebelumnya. Cocokkan redaksi indikator dengan arsip tahun asal.</p>}</div>}
        {!period && <div className={`${panel} px-6 py-14 text-center`}><CalendarDaysIcon className="mx-auto h-10 w-10 text-slate-300 dark:text-slate-600" /><h2 className="mt-4 text-lg font-semibold">Periode belum tersedia</h2><p className={`mx-auto mt-2 max-w-md ${muted}`}>Pilih tahun yang sudah tersedia atau buat periode baru untuk mulai menyusun indikator.</p><button type="button" className={`${button} mt-5`} onClick={() => setShowCreate(true)}><PlusIcon className="h-4 w-4" />Buat tahun baru</button></div>}
        {period && <>
            <details key={period.id} className={`${panel} group`} open={canEdit ? true : undefined}>
                <summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-5 focus-visible:outline-sky-500 [&::-webkit-details-marker]:hidden"><div><h2 className="font-semibold">Informasi & status periode</h2><p className={`mt-1 ${muted}`}>{canEdit ? 'Lengkapi tujuan dan hierarki sebelum mengaktifkan periode.' : 'Lihat tujuan organisasi dan pengaturan status periode.'}</p></div><ChevronRightIcon className="h-5 w-5 shrink-0 text-slate-400 transition group-open:rotate-90" /></summary>
            <form className="space-y-5 border-t border-slate-200 p-5 dark:border-slate-800" onSubmit={e => { e.preventDefault(); metadata.put(route('kinerja.update', period.id)); }}>
                <div className="grid gap-5 lg:grid-cols-2">
                <Field label="Nama organisasi"><input className={input} value={metadata.data.nama_organisasi} disabled={!canEdit} onChange={e => metadata.setData('nama_organisasi', e.target.value)} /></Field>
                <Field label="Tujuan organisasi"><textarea rows={3} className={input} value={metadata.data.tujuan} disabled={!canEdit} onChange={e => metadata.setData('tujuan', e.target.value)} placeholder="Tujuan yang ditampilkan pada dokumen Cascading" /></Field>
                </div>
                {period.status !== 'ditutup' && <div className="flex flex-wrap items-end gap-3"><Field label="Status"><select className={input} value={metadata.data.status} onChange={e => metadata.setData('status', e.target.value)}>{canEdit && <option value="draft">Draft</option>}<option value="aktif">Aktif</option>{!canEdit && <option value="ditutup">Ditutup (baca saja)</option>}</select></Field><button className={button} disabled={metadata.processing || (!canEdit && metadata.data.status !== 'ditutup')}>Simpan periode</button></div>}
                <Errors errors={metadata.errors} />
                <p className={muted}>{canEdit ? 'Setelah aktif, hierarki dikunci dan periode dapat digunakan untuk transaksi.' : 'Periode yang ditutup menjadi baca saja dan tidak dapat dibuka kembali melalui halaman ini.'}</p>
            </form>
            </details>
            <nav aria-label="Bagian pengelolaan indikator" className="flex gap-1 overflow-x-auto border-b border-slate-200 dark:border-slate-800">{[{ id: 'bagan', label: 'Bagan Cascading', icon: Squares2X2Icon }, { id: 'hierarki', label: 'Hierarki indikator', icon: Squares2X2Icon }, { id: 'pemetaan', label: 'Pemetaan copy', icon: ArrowPathIcon }, { id: 'arsip', label: 'Arsip Cascading', icon: FolderOpenIcon }].map(({ id, label, icon: Icon }) => <button type="button" key={id} aria-pressed={tab === id} onClick={() => setTab(id)} className={`inline-flex shrink-0 items-center gap-2 border-b-2 px-4 py-3 text-sm font-semibold transition focus-visible:outline-sky-500 ${tab === id ? 'border-sky-600 text-sky-700 dark:border-sky-400 dark:text-sky-400' : 'border-transparent text-slate-500 hover:border-slate-300 hover:text-slate-800 dark:text-slate-400 dark:hover:text-slate-200'}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>
            {cascadingIssues.length > 0 && <div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-900/20 dark:text-amber-200"><p className="font-semibold">{cascadingIssues.length} data aktif belum terhubung ke bagan</p><p className="mt-1">Perbaiki induk yang tidak aktif atau belum tersedia melalui tab Hierarki indikator sebelum ekspor.</p><ul className="mt-2 list-inside list-disc">{cascadingIssues.slice(0, 10).map(item => <li key={`${item.level}-${item.id}`}>Fitur {item.level} #{item.id}: {item.name}</li>)}</ul></div>}
            {tab === 'bagan' && <CascadingChart key={period.id} tree={cascadingTree} period={period} />}
            {tab === 'hierarki' && <section className="grid min-w-0 gap-5 xl:grid-cols-[210px_minmax(0,1fr)]">
                <aside className="min-w-0"><div className={`${panel} p-3`}><p className="mb-3 px-2 pt-1 text-xs font-semibold uppercase tracking-wider text-slate-400">Tingkat hierarki</p><div className="grid gap-1 sm:grid-cols-2 xl:grid-cols-1">{levelOrder.map(id => <button type="button" key={id} aria-pressed={level === id} onClick={() => { setLevel(id); setEditing(false); setSearch(''); }} className={`flex items-center justify-between gap-2 rounded-xl px-3 py-3 text-left text-sm transition focus-visible:outline-sky-500 ${level === id ? 'bg-sky-50 font-semibold text-sky-700 dark:bg-sky-900/30 dark:text-sky-300' : 'text-slate-600 hover:bg-slate-50 dark:text-slate-400 dark:hover:bg-slate-800'}`}><span>{levels[id]}</span><span className={`rounded-md px-2 py-0.5 text-xs tabular-nums ${level === id ? 'bg-sky-100 dark:bg-sky-900' : 'bg-slate-100 dark:bg-slate-800'}`}>{nodes[id]?.length || 0}</span></button>)}</div></div></aside>
                <div className="min-w-0 space-y-4">
            {!canEdit && <div className="flex gap-2.5 rounded-xl bg-slate-100 p-3 text-sm text-slate-600 dark:bg-slate-800 dark:text-slate-300"><LockClosedIcon className="mt-0.5 h-4 w-4 shrink-0" /><p>Hierarki tahun {period.tahun} bersifat baca saja. Buat draft tahun baru untuk menyesuaikan indikator.</p></div>}
            {editing && <form ref={editor} className={`${panel} scroll-mt-6 space-y-5 border-sky-200 p-5 dark:border-sky-900`} onSubmit={e => { e.preventDefault(); node.post(route('kinerja.nodes', [period.id, level]), { onSuccess: () => setEditing(false) }); }}>
                <div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{node.data.id ? 'Edit' : 'Tambah'} {levels[level].toLowerCase()}</h3><p className={`mt-1 ${muted}`}>Perubahan disimpan pada draft tahun {period.tahun}.</p></div><button type="button" className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Tutup editor indikator" onClick={() => setEditing(false)}><XMarkIcon className="h-5 w-5" /></button></div>
                <div className="grid gap-3 md:grid-cols-2">
                    <Field label="Nama indikator/sasaran *"><textarea autoFocus rows={3} className={input} value={node.data.name} maxLength={255} onChange={e => node.setData('name', e.target.value)} required /></Field>
                    <Field label="Tujuan/sasaran penjelas"><textarea rows={3} className={input} value={node.data.tujuan} maxLength={255} onChange={e => node.setData('tujuan', e.target.value)} /></Field>
                    <Field label="Jabatan penanggung jawab"><input className={input} value={node.data.jabatan} onChange={e => node.setData('jabatan', e.target.value)} /></Field>
                    <Field label="Kode Cascading khusus (opsional)"><input className={input} placeholder="Kosongkan untuk kode otomatis" value={node.data.kode_cascading} onChange={e => node.setData('kode_cascading', e.target.value)} /></Field>
                    <Field label="Urutan tampil"><input type="number" min="0" className={input} value={node.data.sort_order} onChange={e => node.setData('sort_order', e.target.value)} /></Field>
                    {parents[level] && <Field label="Indikator induk"><select required className={input} value={node.data[parents[level][0]]} onChange={e => node.setData(parents[level][0], e.target.value)}>{options(nodes[parents[level][1]])}</select></Field>}
                    {level === '4' && <fieldset className="min-w-0 md:col-span-2"><legend className="mb-2 text-sm font-medium">Unit yang dapat memakai indikator</legend><p className={`mb-3 ${muted}`}>Centang satu atau beberapa unit, atau pilih semua unit.</p><div className="grid max-h-52 gap-2 overflow-y-auto rounded-xl border border-slate-200 p-3 dark:border-slate-700 sm:grid-cols-2">{[{ id: 0, name: 'Semua unit' }, ...locations].map(unit => <label key={unit.id} className="flex cursor-pointer items-start gap-3 rounded-lg p-2 text-sm hover:bg-slate-50 dark:hover:bg-slate-800"><input type="checkbox" className="mt-0.5 rounded border-slate-300 text-sky-600 focus:ring-sky-500 dark:border-slate-600 dark:bg-slate-900" checked={node.data.location_id.map(Number).includes(Number(unit.id))} onChange={e => { const selected = node.data.location_id.map(Number); const id = Number(unit.id); node.setData('location_id', e.target.checked ? (id === 0 ? [0] : [...selected.filter(x => x !== 0), id]) : selected.filter(x => x !== id)); }} /><span>{unit.name}</span></label>)}</div></fieldset>}
                </div>
                <p className={muted}>Kode otomatis mengikuti induk dan urutan: 1 → 1.1 → 1.1.a → 1.1.a.1. Isi kode khusus untuk mengikuti penomoran dokumen, misalnya 1.1.b.</p>
                <label className="flex items-center gap-2.5 text-sm"><input className="rounded border-slate-300 text-sky-600 focus:ring-sky-500 dark:border-slate-600 dark:bg-slate-900" type="checkbox" checked={node.data.is_active} onChange={e => node.setData('is_active', e.target.checked)} />Indikator aktif</label>
                <Errors errors={node.errors} /><div className="flex flex-wrap gap-2 border-t border-slate-100 pt-4 dark:border-slate-800"><button className={button} disabled={node.processing}>{node.processing ? 'Menyimpan…' : 'Simpan indikator'}</button><button type="button" className={secondary} onClick={() => setEditing(false)}>Batal</button></div>
            </form>}
            <div className={`${panel} overflow-hidden`}>
                <div className="space-y-4 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{levels[level]}</h2><p className={`mt-1 ${muted}`}>{nodes[level]?.length || 0} data pada periode {period.tahun}</p></div>{canEdit && <button type="button" className={button} onClick={() => begin()}><PlusIcon className="h-4 w-4" />Tambah</button>}</div><div className="relative"><MagnifyingGlassIcon className="pointer-events-none absolute left-3 top-3 h-5 w-5 text-slate-400" /><input className={`${input} pl-10`} aria-label="Cari indikator" placeholder="Cari nama, jabatan, kode, atau ID…" value={search} onChange={e => setSearch(e.target.value)} /></div></div>
                <div className="relative overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">{levels[level]} tahun {period.tahun}</caption><thead className="border-y border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:border-slate-800 dark:bg-slate-800/40 dark:text-slate-400"><tr><th scope="col" className="px-5 py-3">Nama / Kode Cascading</th><th scope="col" className="px-4 py-3">Penanggung jawab</th><th scope="col" className="px-4 py-3">Status</th>{canEdit && <th scope="col" className="px-4 py-3"><span className="sr-only">Tindakan</span></th>}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{visibleRows.map(x => <tr key={x.id} className="transition hover:bg-slate-50/80 dark:hover:bg-slate-800/40"><td className="min-w-[220px] px-5 py-4 align-top"><div className="mb-1.5 flex flex-wrap items-center gap-2 text-xs text-slate-400"><span>#{x.id}</span>{(x.display_code || x.kode_cascading) && <span className="rounded bg-slate-100 px-1.5 py-0.5 font-medium text-slate-600 dark:bg-slate-800 dark:text-slate-300">{x.display_code || x.kode_cascading}</span>}</div><p className="max-w-xl whitespace-normal break-words font-medium leading-relaxed">{x.name}</p></td><td className="min-w-[160px] px-4 py-4 align-top text-slate-600 dark:text-slate-400"><p className="max-w-xs whitespace-normal break-words leading-relaxed">{x.jabatan || <span className="italic text-slate-400">Belum diisi</span>}</p></td><td className="px-4 py-4 align-top"><Status status={x.is_active ? 'aktif' : 'nonaktif'} /></td>{canEdit && <td className="px-4 py-4 align-top"><button type="button" className="inline-flex items-center gap-1.5 rounded-lg p-2 text-sm font-semibold text-sky-600 hover:bg-sky-50 focus-visible:ring-2 focus-visible:ring-sky-500 dark:text-sky-400 dark:hover:bg-sky-900/30" aria-label={`Edit ${x.name}`} onClick={() => begin(x)}><PencilSquareIcon className="h-4 w-4" />Edit</button></td>}</tr>)}</tbody></table></div>
                {rows.length === 0 && <div className="px-5 py-12 text-center"><MagnifyingGlassIcon className="mx-auto h-9 w-9 text-slate-300 dark:text-slate-600" /><p className="mt-3 font-semibold">{search ? 'Indikator tidak ditemukan' : 'Belum ada data pada tingkat ini'}</p><p className={`mt-1 ${muted}`}>{search ? 'Coba kata kunci lain atau kosongkan pencarian.' : canEdit ? 'Gunakan tombol Tambah untuk menyusun hierarki periode ini.' : 'Pilih tingkat hierarki lain untuk melihat indikator.'}</p>{search && <button type="button" className="mt-3 text-sm font-semibold text-sky-600 dark:text-sky-400" onClick={() => setSearch('')}>Hapus pencarian</button>}</div>}
                <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 px-5 py-4 dark:border-slate-800"><p className="text-xs text-slate-500 dark:text-slate-400">{rows.length ? `${(currentPage - 1) * 15 + 1}–${Math.min(currentPage * 15, rows.length)} dari ${rows.length} data` : '0 data'}</p><div className="flex items-center gap-2"><button type="button" className={`${secondary} p-2`} aria-label="Halaman sebelumnya" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}><ChevronLeftIcon className="h-4 w-4" /></button><span className="text-xs tabular-nums text-slate-500 dark:text-slate-400">{currentPage} / {pageCount}</span><button type="button" className={`${secondary} p-2`} aria-label="Halaman berikutnya" disabled={currentPage === pageCount} onClick={() => setPage(currentPage + 1)}><ChevronRightIcon className="h-4 w-4" /></button></div></div>
            </div>
            </div></section>}
            {tab === 'pemetaan' && <section className={`${panel} p-5 sm:p-6`}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="text-lg font-semibold">Pemetaan indikator pengganti</h2><p className={`mt-2 max-w-2xl ${muted}`}>Hubungkan indikator sumber dengan indikator tahun {period.tahun} jika indikator berubah. Gunakan ID sumber dari preview copy risk register.</p></div><a className={`${secondary} shrink-0`} href={route('riskRegisterCopy.index')}>Buka copy risiko</a></div>
                {period.status === 'ditutup' ? <div className="mt-6 flex gap-3 rounded-xl bg-slate-100 p-4 text-sm text-slate-600 dark:bg-slate-800 dark:text-slate-300"><LockClosedIcon className="h-5 w-5 shrink-0" />Periode sudah ditutup. Pemetaan indikator tidak dapat diubah.</div> : <form className="mt-6 space-y-5" onSubmit={e => { e.preventDefault(); mapping.post(route('kinerja.mapping')); }}><div className="grid items-end gap-4 lg:grid-cols-3"><Field label="ID indikator sumber"><input required min="1" type="number" className={input} placeholder="ID dari preview copy" value={mapping.data.source_indicator_id} onChange={e => mapping.setData('source_indicator_id', e.target.value)} /></Field><div className="min-w-0 lg:col-span-2"><Field label={`Indikator tujuan ${period.tahun}`}><select required className={input} value={mapping.data.target_indicator_id} onChange={e => mapping.setData('target_indicator_id', e.target.value)}>{options((nodes['4'] || []).filter(x => x.is_active))}</select></Field></div></div><p className={muted}>Pemetaan berlaku untuk copy berikutnya. Risk register yang sudah tersimpan tetap menggunakan indikatornya.</p><Errors errors={mapping.errors} /><button className={button} disabled={mapping.processing}><ArrowPathIcon className="h-4 w-4" />{mapping.processing ? 'Menyimpan…' : 'Simpan pemetaan'}</button></form>}
            </section>}
            {tab === 'arsip' && <section className={`${panel} overflow-hidden`}><div className="border-b border-slate-200 p-5 dark:border-slate-800 sm:p-6"><h2 className="text-lg font-semibold">Arsip Cascading {period.tahun}</h2><p className={`mt-2 ${muted}`}>Unduh kembali dokumen dengan data yang tersimpan saat ekspor dibuat. Menampilkan hingga 20 arsip terbaru.</p></div>{exports.length ? <ul className="divide-y divide-slate-100 dark:divide-slate-800">{exports.map(x => <li key={x.id} className="flex flex-wrap items-center justify-between gap-4 p-5 sm:px-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-2.5 text-emerald-600 dark:bg-emerald-900/30 dark:text-emerald-400"><FolderOpenIcon className="h-5 w-5" /></div><div><p className="text-sm font-semibold">Cascading {period.tahun} <span className="font-normal text-slate-400">#{x.id}</span></p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{x.created_at} · Excel</p></div></div><a className={secondary} href={route('kinerja.exportArchive', x.id)}><ArrowDownTrayIcon className="h-4 w-4" />Unduh</a></li>)}</ul> : <div className="px-5 py-12 text-center"><FolderOpenIcon className="mx-auto h-10 w-10 text-slate-300 dark:text-slate-600" /><h3 className="mt-4 font-semibold">Belum ada arsip ekspor</h3><p className={`mt-2 ${muted}`}>Buat ekspor pertama untuk menyimpan dokumen Cascading periode ini.</p><a className={`${button} mt-5`} href={route('kinerja.export', period.id)}><ArrowDownTrayIcon className="h-4 w-4" />Ekspor Cascading</a></div>}</section>}
        </>}
    </div>;
}
Index.layout = page => <App>{page}</App>;
